export const green = '#2a363b'
export const white = '#f4f6f6'
export const flesh = '#fecea8'
export const deeporange = '#ff847c'
export const lightred = '#e84a5f'
export const orange = '#F8b195'
export const blue = '#007acc'
